//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinancialResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinancialResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssetManager.Resources.FinancialResources", typeof(FinancialResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Return of interest.
        /// </summary>
        public static string AverageROI {
            get {
                return ResourceManager.GetString("AverageROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges sum.
        /// </summary>
        public static string ChargesSum {
            get {
                return ResourceManager.GetString("ChargesSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnings repartition.
        /// </summary>
        public static string EarningsRepartition {
            get {
                return ResourceManager.GetString("EarningsRepartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebit.
        /// </summary>
        public static string Ebit {
            get {
                return ResourceManager.GetString("Ebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebit estimate.
        /// </summary>
        public static string EbitEstimate {
            get {
                return ResourceManager.GetString("EbitEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnings per meter squared.
        /// </summary>
        public static string EPMS {
            get {
                return ResourceManager.GetString("EPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income tax.
        /// </summary>
        public static string IncomeTax {
            get {
                return ResourceManager.GetString("IncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators based on payments.
        /// </summary>
        public static string IndicatorsPayments {
            get {
                return ResourceManager.GetString("IndicatorsPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators based on previsions.
        /// </summary>
        public static string IndicatorsPrevision {
            get {
                return ResourceManager.GetString("IndicatorsPrevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate.
        /// </summary>
        public static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments in delay.
        /// </summary>
        public static string PaymentsInDelay {
            get {
                return ResourceManager.GetString("PaymentsInDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rents sum.
        /// </summary>
        public static string RentsSum {
            get {
                return ResourceManager.GetString("RentsSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenues per year.
        /// </summary>
        public static string RevenuesPerYear {
            get {
                return ResourceManager.GetString("RevenuesPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return on investment.
        /// </summary>
        public static string ROI {
            get {
                return ResourceManager.GetString("ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total return.
        /// </summary>
        public static string TotalReturn {
            get {
                return ResourceManager.GetString("TotalReturn", resourceCulture);
            }
        }
    }
}
